---
name: build-and-test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.17.x
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test
